version: "3"
services:
  server:
    build:
      dockerfile: server.dockerfile
    ports:
      - "8000:8000"
    environment:
      - DB_CONNECTION_STRING=$DB_CONNECTION_STRING
  web:
    build:
      dockerfile: ./web.dockerfile
      args:
        - VITE_API_URL=$VITE_API_URL
    ports:
      - "80:80"
